server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: ${datasource-url}
    username: ${datasource-un}
    password: ${datasource-pw}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 192.168.204.130:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

management:
  defaults:
    metrics:
      export:
        enabled: false

  prometheus:
    metrics:
      export:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health, prometheus

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0 #trace every request, dial down to 0.1 for 10% of requests, 0.01 for 1% of requests, etc.

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://192.168.204.130:4318/v1/traces