name: Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, linux, minikube]

    steps:
      - name: Runner information
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
          hostname

      - name: Check Docker
        run: docker --version

      - name: Check kubectl
        run: kubectl version --client

      - name: Check Minikube
        run: minikube status

      - name: Check Kubernetes
        run: kubectl get nodes

      - name: Check pods
        run: kubectl get pods -A